version: 0.0
os: windows
files:
  - source: /binaries
    destination: c:/quoterservice
hooks:
  BeforeInstall:
    - location: scripts/uninstall.bat
      timeout: 300
  AfterInstall:
    - location: scripts/install.bat
      timeout: 300
  ValidateService:
    - location: scripts/check_port_open.bat
      timeout: 300
	  

